version: '3'
services:
  mongodb:
    image: mongo:4.2.15
    container_name: mongo-pwndoc-ng
    volumes:
      - mongo-data:/data/db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_DB:pwndoc
    networks:
      - backend

  backend:
    build: ./backend
    image: pwndoc-ng/pwndoc-ng:backend
    container_name: pwndoc-ng-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongodb
    environment:
      - COLLAB_WEBSOCKET_PORT=8440
    restart: always
    ports:
      - 4242:4242
    links:
      - mongodb
    networks:
      - backend

  frontend:
    build: ./frontend
    image: pwndoc-ng/pwndoc-ng:frontend
    container_name: pwndoc-ng-frontend
    restart: always
    ports:
      - 8443:8443
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
      driver: bridge
